version: "3"

services:
  jupyterlab:
    image: mi2428/jupyterlab:latest
    # image: docker.pkg.github.com/mi2428/jupyterlab/jupyterlab:latest
    build:
      context: .
    environment:
      GRANT_SUDO: "yes"
      USE_LSP: "no"
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work

